// <auto-generated />
namespace DbModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfasd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfasd));
        
        string IMigrationMetadata.Id
        {
            get { return "201305271217194_dfasd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
