// <auto-generated />
namespace DbModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdf));
        
        string IMigrationMetadata.Id
        {
            get { return "201307111210463_dfdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
