// <auto-generated />
namespace DbModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfdfdf1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdfdf1));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101201511_dfdfdf1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
