// <auto-generated />
namespace DbModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asdfasdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdfasdf));
        
        string IMigrationMetadata.Id
        {
            get { return "201307100639408_asdfasdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
