// <auto-generated />
namespace DbModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfdfdf2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdfdf2));
        
        string IMigrationMetadata.Id
        {
            get { return "201307171007004_dfdfdf2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
