// <auto-generated />
namespace DbModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class fdfasdffflfpf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fdfasdffflfpf));
        
        string IMigrationMetadata.Id
        {
            get { return "201403070916478_fdfasdffflfpf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
