// <auto-generated />
namespace DbModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class dfdfa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdfa));
        
        string IMigrationMetadata.Id
        {
            get { return "201501211123230_dfdfa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
