// <auto-generated />
namespace DbModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adfa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adfa));
        
        string IMigrationMetadata.Id
        {
            get { return "201609280755097_adfa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
